name: Maintenance

on:
  push:
    branches:
      - feature/**
      - fix/**
      - docs/**
      - refactor/**
      - test/**
      - ci/**
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci --omit=dev --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Stylelint
        run: npm run stylelint
